name: Salt Security Plugin CD

on: 
  workflow_call:
    inputs:
      filename:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      S3_BUCKET:
        required: true
      AWS_REGION:
        required: true
      MAIL_USERNAME:
      MAIL_PASSWORD:
      TO_LIST:
      
      
defaults:
  run:
    shell: bash
    working-directory: ./
    
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading build from cache
        uses: actions/download-artifact@v3
        with:
          name: latest-build
          path: dist
      - name: Uploading to S3
        uses: zdurham/s3-upload-github-action@master
        if: success()
        env:
          FILE: dist/${{ inputs.filename }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_KEY: ${{ inputs.filename }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: New Build uploaded
          to: ${{ secrets.TO_LIST }}
          from: notificationgithubactions
          body: Build job of ${{github.repository}} completed successfully & File ${{ inputs.filename }} uploaded to s3 bucket ${{ secrets.S3_BUCKET }}.
       

    