name: Salt Security Plugin CD

on: 
  workflow_call:
    inputs:
      file_name:
        required: true
        type: string
    secrets:
      AWS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_BUCKET:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string
      
defaults:
  run:
    shell: bash
    working-directory: ./
    
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading build from cache
        uses: actions/download-artifact@v3
        with:
          name: latest-build
          path: dist/${{ inputs.file_name }}
      - Uploading to S3
        uses: zdurham/s3-upload-github-action@master
        if: success()
        env:
          FILE: dist/${{ inputs.file_name }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: ${{ secrets.AWS_BUCKET }}
          S3_KEY: ${{ inputs.file_name }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AOT_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AOT_SECRET_ACCESS_KEY}}

    