name: Salt Security Plugin CI

on: 
  workflow_call:
    inputs:
      buildDir:
        required: false
        type: string
        
defaults:
  run:
    shell: bash
    working-directory: ./
      
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Cache Maven packages
        if: always()
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Test
        if: always()
        run: |
          cd ${{inputs.buildDir || ./}}
          mvn -B test --file pom.xml
      - name: Build
        if: always()
        run: |
          cd ${{inputs.buildDir || ./}}
          mvn -B package -DskipTests --file pom.xml