name: Salt Security Plugin CD

on: 
  workflow_call:
    inputs:
      file_name:
        required: true
        type: string
    secrets:
      AWS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_BUCKET:
        required: true
      DESTINATION_DIR:
        required: true
      
defaults:
  run:
    shell: bash
    working-directory: ./
    
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: latest-build
          path: dist/${{ inputs.file_name }}
      - uses: shallwefootball/s3-upload-action@master
        name: Upload S3
        id: S3
        if: success()
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: dist/${{ inputs.file_name }}
          destination_dir: ${{ secrets.DESTINATION_DIR }}

    