name: Salt Security Plugin CD

on: [workflow_call]
      
defaults:
  run:
    shell: bash
    working-directory: ./
    
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: latest-build
          path: dist/${{ inputs.file_name }}
      - name: print
        run: |
          echo "${{ inputs.file_name }}"

    