name: Salt Security Plugin CD

on: 
  workflow_call:
    inputs:
      filename:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      S3_BUCKET:
        required: true
      AWS_REGION:
        required: true
      
defaults:
  run:
    shell: bash
    working-directory: ./
    
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading build from cache
        uses: actions/download-artifact@v3
        with:
          name: latest-build
          path: dist
      - name: Upload build to s3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.S3_BUCKET }}
          source_dir: dist

    