name: Salt Security Plugin CI

on: 
  workflow_call:
    inputs:
      buildDir:
        required: false
        type: string
      
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Cache Maven packages
        if: always()
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Test
        if: always()
        run: |
          echo "${{inputs.buildDir == null}}"
          echo "${{inputs.buildDir == ''}}"
          if [ ${{inputs.buildDir != ''}} ]; then
            cd ${{inputs.buildDir}}
          fi
          mvn -B test --file pom.xml
      - name: Build
        if: always()
        run: |
          if [ ${{inputs.buildDir != ''}} ]; then
            cd ${{inputs.buildDir}}
          fi
          mvn -B package -DskipTests --file pom.xml